name: todo_app
description: A beautiful application to manage all your Work.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  go_router: ^14.7.2
  google_fonts: ^6.2.1
  path: ^1.9.1
  path_provider: ^2.1.5
  sembast: ^3.8.2
  shared_preferences: ^2.5.1
  riverpod_lint: ^2.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
